openapi: 3.0.3
info:
  title: iCARE - An Intelligent Car Budgeting Assistant
  version: 1.0.1
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: coe
  - name: car
  
paths:
  /coe/prediction:
    get:
      tags:
        - coe
      summary: Get COE prediction by category
      operationId: getCoePredictionByCategory
      parameters:
        - name: category
          in: query
          description: Category that need to be considered for filter
          required: false
          schema:
            type: string
            enum:
              - A
              - B
              - C
              - D
              - E
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryPrediction'          
        default:
          description: 4xx, 5xx error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
                
  /cars/suggest:            
    post:
      tags:
        - car
      summary: Suggest cars based on user car preference
      operationId: suggestCarsByUserPreference
      requestBody:
        description: User car preference
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarPreference'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'  
        default:
          description: 4xx, 5xx error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          

  /cars/{id}:
    get:
      tags:
        - car
      summary: Get car by Id
      operationId: getCarById
      parameters:
        - name: id
          in: path
          description: Id of car to retrieve
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'          
        default:
          description: 4xx, 5xx error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

components:
  schemas:
    CategoryPrediction:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          enum:
            - Category A
            - Category B
            - Category C
            - Category D
            - Category E
        series:
          type: array
          items:
            $ref: '#/components/schemas/Predictions'
          
  
    Predictions:
      type: object
      properties:
        name:
          type: string
        value:
          type: number
        min:
          type: number
        max:
          type: number
          
    Car:
      type: object
      properties:
        id:
          type: integer
        brand: 
          type: string
        model:
          type: string
        variant:
          type: string
        type:
          type: string
        priceBeforeCoe:
          type: number
        priceAfterCoe:
          type: number
        bestBiddingExercise:
          type: string
        photo:
          type: string
          
    CarPreference:
      type: object
      properties:
        startYear:
          type: string
        startMonth:
          type: string
        endYear:
          type: string
        endMonth:
          type: string
        brand:
          type: array
          items: 
            type: string
        type:
          type: array
          items: 
            type: string
        budget:
          type: number
      
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
