/**
 * iCARE - An Intelligent Car Budgeting Assistant
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CarPreference { 
    startYear?: string;
    startMonth?: string;
    endYear?: string;
    endMonth?: string;
    brand?: Array<string>;
    type?: Array<string>;
    budget?: number;
}